image: 'rust:latest'

# Use cargo to test the project
test:cargo:
  script:
    - rustup default nightly
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
