image: 'rust:latest'

before_script:
    - rustup default nightly
    - rustc --version && cargo --version  # Print version info for debugging
    - rustup component add clippy

test:
  script:
    - cargo test --workspace --verbose

lint:
  script:
    - cargo clippy