[twitter]
alias = "tw"
# Default page should be required
default = "https://twitter.com"

[twitter.pages]
# Should have an option to pass params with no prefix
# while 'default' means no params, only the command
search = { prefix = "-s", url = "https://twitter.com/search?q={encoded}" }
user = { prefix = "@", url = "https://twitter.com/{raw}" }




[github]
alias = "gh"
default = "https://github.com"

[github.pages]
repo = { prefix = "-r", url = "https://github.com/{raw}" }
use = { prefix = "@", url = "https://github.com/{raw}" }